language: node_js
sudo: false
node_js:
  - '6.9'

cache:
  directories:
     - ./node_modules
     - ./typings

install:
  - npm i -g typings
  - npm i
  - typings install

before_script:

script:
  - npm run test
